//========================================================================================================================
//  METHOD DETAILS: Identify what is type of the node generated by the figma plugin
//========================================================================================================================

export function setNodeType(name: any){
    let trimmedType = name.substring(0,3).toLowerCase();
  
    switch(trimmedType){
      case 'btn':
        return 'Button';
      case 'biv':
        return 'Button with Image Vertical'
      case 'bih':
        return 'Button with Image Horizontal'
      case 'tbt':
        return 'Text Button';
      case 'obt':
        return 'Outline Button';
      case 'txt':
        return 'TextFormField';
      case 'lbl':
        return 'Label';
      case 'png':
      case 'svg':
      case 'jpg':
      case 'bgc':
      case 'abg':
      case 'imn':
        return 'Image';      
      case 'bgi':
        return 'Background Image';
      case 'cln':
        return 'Column';
      case 'row':
        return 'Row';
      case 'lst':
        return 'ListView';
      case 'ctn':
        return 'Container';
      case 'crd':
        return 'Card';
      case 'swt':
        return 'Switch';
      case 'div':
        return 'Divider';
      case 'rad':
        return 'Radio';
      case 'chk':
        return 'Checkbox';
      case 'cck':
        return 'Circular Checkbox';
      case 'txa':
        return 'Text Area';
      case 'grd':
        return 'GridView';
      case 'apb':
        return 'AppBar';
      case 'ibt':
        return 'Icon Button';
      case 'drp':
        return 'Dropdown';
      case 'dri':
        return 'Dropdown Item';
      case 'dtp':
        return 'Date Picker';
      case 'tmp':
        return 'Time Picker';
      case 'bdg':
        return 'Badge';
      case 'wrp':
        return 'Wrap';
      case 'car':
        return 'CircleAvatar';
      case 'bnb':
        return 'BottomNavigationBar';
      case 'bni':
        return 'BottomNavigationBarItem';
      case 'dwr':
        return 'Drawer';
      case 'dwh':
        return 'Drawer Header';
      case 'ltl':
        return 'List Tile';                                                                
      case 'sth':
        return 'Stepper Horizontal';
      case 'sph':
        return 'Step Horizontal';
      case 'stv':
        return 'Stepper Vertical';
      case 'spv':
        return 'Step Vertical';           
      case 'tbr':
        return 'TabBar';
      case 'tab':
        return 'Tab';
      case 'tbv':
        return 'TabBarView';        
      case 'mtl':
        return 'Material';
      case 'pad':
        return 'Padding';
      case 'ept':
        return 'Expansion Tile';
      case 'ett':
        return 'Expansion Tile Title'; 
      case 'ets':
        return 'Expansion Tile Subtitle';
      case 'eti':
        return 'Expansion Tile Image';
      case 'cpb':
        return 'Circular Progress Bar';
      case 'lpb':
        return 'Linear Progress Bar';     
      case 'pbc':
        return 'Progress Bar Color';                          
      default:
        return 'Default Container'
    }
  }